apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-gpt-ingress
spec:
  ingressClassName: haproxy
  rules:
  - host: personal-gpt-maths.nrp-nautilus.io
    http:
      paths:
      - backend:
          service:
            name: personal-gpt-service 
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - personal-gpt-maths.nrp-nautilus.io