# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: personal-gpt-ingress
#   namespace: personal-gpt
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/rewrite-target: "/"
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /personal-gpt
#         pathType: Prefix
#         backend:
#           service:
#             name: personal-gpt-service
#             port:
#               number: 80