apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: personal-gpt-hpa
  namespace: personal-gpt
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: personal-gpt
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30  # Scale down after 30 seconds
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 10  # Scale up after 10 seconds
      policies:
        - type: Percent
          value: 100
          periodSeconds: 10